### ISSUE TITLE
Immediate Crash Upon Startup.

### ISSUE THREAD

**Issue by JustLiam040** [SilentChaos512/SilentLib#11]
Im not too sure what is causing this issue but when testing for the issue i found it was definitely ScalingHealth. I tried different versios (The modpack im working on requires 3.0x due to having extended days etc) and however each time got the exact same crash. Copied below is the shortended summary and attached will be the full log. When removing scaling health everything loads up perfectly, hence why im sure that mod is the issue.

Copied log:
-----------

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/silentchaos512/lib/registry/IRegistrationHandler

[crash-2018-08-24_09.14.59-client.txt](https://github.com/SilentChaos512/SilentLib/files/2317587/crash-2018-08-24_09.14.59-client.txt)

**Comment by SilentChaos512** [comment]
Update Scaling Health to the latest version. The 3.0.x versions of Silent Lib are not compatible with older builds.

**Comment by P3rf3ctXZer0** [comment]
::Key - u- Universal -b Beta ::
u-ScalingHealth-1.12.2-1.3.26-127-b isn't this the correct version?

**Comment by P3rf3ctXZer0** [comment]
Crash Log
https://gist.github.com/P3rf3ctXZer0/161ca621ee237e5e00d709d94a8834a1

**Comment by SilentChaos512** [comment]
@P3rf3ctXZer0 Looks like you have the latest version of everything. There shouldn't be any references to `IRegistrationHandler` left...

**Comment by P3rf3ctXZer0** [comment]
Exactly.
I have no idea why I am crashing.

**Comment by P3rf3ctXZer0** [comment]
I am no longer crashing now ... here are
![2018-08-26 22_37_09-window](https://user-images.githubusercontent.com/10351221/44639278-ac836380-a980-11e8-9bc2-dc834d584112.jpg)

 the mods I am using.

**Comment by Y0ungSandwich** [comment]
Seeing the same on Mech & Magic modpack
https://www.atlauncher.com/pack/MechMagic

https://gist.github.com/Y0ungSandwich/2e9b4c7b28cac54810112f651afed7bc

SilentLib: 3.0.1-145
Silent's Gems: 2.8.2-293
Scaling Health: 1.3.26-127

**Comment by SilentChaos512** [comment]
@Y0ungSandwich Update SG Extra Parts to the latest version.
